// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: tachiyomi.proto

package backup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Backup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @ProtoNumber(1) val backupManga: List<BackupManga>
	BackupManga []*BackupManga `protobuf:"bytes,1,rep,name=backupManga" json:"backupManga,omitempty"`
}

func (x *Backup) Reset() {
	*x = Backup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tachiyomi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Backup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backup) ProtoMessage() {}

func (x *Backup) ProtoReflect() protoreflect.Message {
	mi := &file_tachiyomi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backup.ProtoReflect.Descriptor instead.
func (*Backup) Descriptor() ([]byte, []int) {
	return file_tachiyomi_proto_rawDescGZIP(), []int{0}
}

func (x *Backup) GetBackupManga() []*BackupManga {
	if x != nil {
		return x.BackupManga
	}
	return nil
}

type BackupManga struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @ProtoNumber(1) var source: Long
	Source *int64 `protobuf:"varint,1,req,name=source" json:"source,omitempty"`
	// @ProtoNumber(2) var url: String
	Url *string `protobuf:"bytes,2,req,name=url" json:"url,omitempty"`
}

func (x *BackupManga) Reset() {
	*x = BackupManga{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tachiyomi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupManga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupManga) ProtoMessage() {}

func (x *BackupManga) ProtoReflect() protoreflect.Message {
	mi := &file_tachiyomi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupManga.ProtoReflect.Descriptor instead.
func (*BackupManga) Descriptor() ([]byte, []int) {
	return file_tachiyomi_proto_rawDescGZIP(), []int{1}
}

func (x *BackupManga) GetSource() int64 {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return 0
}

func (x *BackupManga) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

var File_tachiyomi_proto protoreflect.FileDescriptor

var file_tachiyomi_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x61, 0x63, 0x68, 0x69, 0x79, 0x6f, 0x6d, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x38, 0x0a, 0x06, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x2e, 0x0a, 0x0b, 0x62,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x0b,
	0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x22, 0x37, 0x0a, 0x0b, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70,
}

var (
	file_tachiyomi_proto_rawDescOnce sync.Once
	file_tachiyomi_proto_rawDescData = file_tachiyomi_proto_rawDesc
)

func file_tachiyomi_proto_rawDescGZIP() []byte {
	file_tachiyomi_proto_rawDescOnce.Do(func() {
		file_tachiyomi_proto_rawDescData = protoimpl.X.CompressGZIP(file_tachiyomi_proto_rawDescData)
	})
	return file_tachiyomi_proto_rawDescData
}

var file_tachiyomi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tachiyomi_proto_goTypes = []interface{}{
	(*Backup)(nil),      // 0: Backup
	(*BackupManga)(nil), // 1: BackupManga
}
var file_tachiyomi_proto_depIdxs = []int32{
	1, // 0: Backup.backupManga:type_name -> BackupManga
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tachiyomi_proto_init() }
func file_tachiyomi_proto_init() {
	if File_tachiyomi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tachiyomi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Backup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tachiyomi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupManga); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tachiyomi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tachiyomi_proto_goTypes,
		DependencyIndexes: file_tachiyomi_proto_depIdxs,
		MessageInfos:      file_tachiyomi_proto_msgTypes,
	}.Build()
	File_tachiyomi_proto = out.File
	file_tachiyomi_proto_rawDesc = nil
	file_tachiyomi_proto_goTypes = nil
	file_tachiyomi_proto_depIdxs = nil
}
